import { defineField, defineType } from "sanity";

export const factCheck = defineType({
  name: "factCheck",
  title: "Fact check",
  type: "document",
  groups: [
    { name: "claim", title: "Claim", default: true },
    { name: "review", title: "Review" },
    { name: "publishing", title: "Publishing" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Public title",
      type: "string",
      group: "claim",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "publishing",
      options: { source: "title" },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "claim",
      title: "Claim reviewed",
      type: "text",
      rows: 4,
      group: "claim",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "claimant",
      title: "Claimant",
      type: "string",
      group: "claim",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "claimOrigin",
      title: "Claim origin",
      type: "string",
      group: "claim",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "claimDate",
      title: "Claim date",
      type: "date",
      group: "claim",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "reviewDate",
      title: "Review date",
      type: "date",
      group: "publishing",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "verdict",
      title: "Verdict",
      type: "string",
      group: "review",
      options: {
        list: ["True", "Mostly true", "Mixed", "Misleading", "False", "Unproven"],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "conclusion",
      title: "Short conclusion",
      type: "text",
      rows: 3,
      group: "review",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "analysis",
      title: "Full analysis",
      type: "bodyContent",
      group: "review",
      validation: (rule) => rule.required().min(1),
    }),
    defineField({
      name: "evidence",
      title: "Evidence",
      type: "array",
      group: "review",
      of: [{ type: "documentAttachment" }, { type: "editorialImage" }],
    }),
    defineField({
      name: "sources",
      title: "Sources",
      type: "sourceNote",
      group: "review",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "methodology",
      title: "Methodology",
      type: "text",
      rows: 4,
      group: "review",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "reviewer",
      title: "Reviewer",
      type: "reference",
      group: "review",
      to: [{ type: "person" }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "factChecker",
      title: "Fact checker",
      type: "reference",
      group: "review",
      to: [{ type: "person" }],
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "corrections",
      title: "Corrections",
      type: "array",
      group: "review",
      of: [{ type: "correctionBlock" }],
    }),
    defineField({
      name: "relatedClaims",
      title: "Related claims",
      type: "array",
      group: "review",
      of: [{ type: "reference", to: [{ type: "factCheck" }] }],
    }),
    defineField({
      name: "image",
      title: "Lead image",
      type: "editorialImage",
      group: "claim",
    }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "publishing" }),
  ],
  preview: {
    select: {
      title: "title",
      verdict: "verdict",
      date: "reviewDate",
      media: "image",
    },
    prepare: ({ title, verdict, date, media }) => ({
      title,
      subtitle: [verdict, date].filter(Boolean).join(" · "),
      media,
    }),
  },
});

